project:
  type: website
  output-dir: docs

website:
  title: "Laura Lyman's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: test.qmd
        text: STAT-244SC
        

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    
    bootstrap:
      defaults:
        navbar-bg: green
    
editor: visual

