## Online Server Runs Linux

```         
ssh-add ~/.ssh/id_ed25519
```

Add the SSH public key to your account on GitHub. For more information, see [Adding a new SSH key to your GitHub account](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account).

Copy the SSH public key to your clipboard.

When copying your key, don't add any newlines or whitespace.

```         
$ cat ~/.ssh/id_ed25519.pub
```

Now to to the Github website!

1.  In the upper-right corner of any page on GitHub, click your profile photo, then click **Settings**.

<!-- -->

2.  In the "Access" section of the sidebar, click **SSH and GPG keys**.

3.  Click **New SSH key** or **Add SSH key**.

4.  In the "Title" field, add a descriptive label for the new key. For example, if you're using a personal laptop, you might call this key "Personal laptop".

5.  Select the type of key, either authentication or signing. For more information about commit signing, see [About commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification).

6.  In the "Key" field, paste your public key.

7.  Click **Add SSH key**.

8.  If prompted, confirm access to your account on GitHub.

Check to see if your `~/.ssh/config` file exists in the default location.

```         
$ open ~/.ssh/config
```

If this file doesn't exist,

`touch ~/.ssh/config`

# Specific to Mac OSX

Documentation: <https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent?platform=mac>

`eval "$(ssh-agent -s)"`

### MacOS Sierra 10.2.2 or later

If you're using macOS Sierra 10.12.2 or later, you will need to modify your `~/.ssh/config` file to automatically load keys into the ssh-agent and store passphrases in your keychain.

Check to see if your `~/.ssh/config` file exists in the default location.

```         
$ open ~/.ssh/config
```

If this file doesn't exist,

`touch ~/.ssh/config`

```         
Host github.com
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_ed25519
```

-   If you see a `Bad configuration option: usekeychain` error, add an additional line to the configuration's' `Host *.github.com` section.

```         
Host github.com
  IgnoreUnknown UseKeychain
```

Add your SSH private key to the ssh-agent and store your passphrase in the keychain.

```         
ssh-add --apple-use-keychain ~/.ssh/id_ed25519
```
